env:
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  no-console: 0,
  quote-props: 0,
  for-direction: 0,
  no-plusplus: 0,
  consistent-return: 0,
  no-mixed-operators: 0,
}
